import type { Metadata } from "next";
import "./globals.scss";
import {Inter} from 'next/font/google';
import {ClientProviders} from '@/app/providers';

const inter = Inter({
    weight: ['300', '400', '500', '700'],
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-inter',
});

export const metadata: Metadata = {
    title: "Configurator Frontend",
    description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
    return (
        <html lang="en" data-color-scheme="light">
            <body className={`${inter.variable} antialiased`}>
                <ClientProviders>{children}</ClientProviders>
            </body>
        </html>
    );
}
