export const enum CatalogueTags {
    GENERAL_COLOURS = "GENERAL_COLOURS",
    GENERAL_MANUFACTURERS = "GENERAL_MANUFACTURERS",

    PCIE_BRACKETS = "PCIE_BRACKETS",
    PCIE_VERSIONS = "PCIE_VERSIONS",
    PCIE_SIZES = "PCIE_SIZES",
    PCIE_SLOTS = "PCIE_SLOTS",

    M2_FORM_FACTORS = "M2_FORM_FACTORS",
    M2_KEYS = "M2_KEYS",
    M2_SLOTS = "M2_SLOTS",

    IO_CONNECTORS = "IO_CONNECTORS",

    MEMORY_FORM_FACTORS = "MEMORY_FORM_FACTORS",
    MEMORY_TYPES = "MEMORY_TYPES",
    MEMORY_KITS = "MEMORY_KITS",

    GRAPHICS_CARD_CHIPSETS = "GRAPHICS_CARD_CHIPSETS",
    GRAPHICS_CARD_UNITS = "GRAPHICS_CARD_UNITS",

    FAN_PACKS = "FAN_PACKS",
    FAN_SIZES = "FAN_SIZES",

    COOLER_UNITS = "COOLER_UNITS",
    COOLER_RADIATOR_SIZES = "COOLER_RADIATOR_SIZES",

    CENTRAL_PROCESSOR_CHANNELS = "CENTRAL_PROCESSOR_CHANNELS",
    CENTRAL_PROCESSOR_SOCKETS = "CENTRAL_PROCESSOR_SOCKETS",
    CENTRAL_PROCESSOR_MICROARCHITECTURES = "CENTRAL_PROCESSOR_MICROARCHITECTURES",
    CENTRAL_PROCESSOR_SERIES = "CENTRAL_PROCESSOR_SERIES",
    CENTRAL_PROCESSOR_CORE_FAMILIES = "CENTRAL_PROCESSOR_CORE_FAMILIES",
    CENTRAL_PROCESSOR_UNITS = "CENTRAL_PROCESSOR_UNITS",

    CASE_UNITS = "CASE_UNITS",
    CASE_SIZES = "CASE_SIZES",
    CASE_MATERIALS = "CASE_MATERIALS",
    CASE_PANELS = "CASE_PANELS",

    MOTHERBOARD_CHIPSETS = "MOTHERBOARD_CHIPSETS",
    MOTHERBOARD_UNITS = "MOTHERBOARD_UNITS",
    MOTHERBOARD_FORM_FACTORS = "MOTHERBOARD_FORM_FACTORS",

    POWER_SUPPLY_CONNECTORS = "POWER_SUPPLY_CONNECTORS",
    POWER_SUPPLY_EFFICIENCY_RATINGS = "POWER_SUPPLY_EFFICIENCY_RATINGS",
    POWER_SUPPLY_FORM_FACTORS = "POWER_SUPPLY_FORM_FACTORS",
    POWER_SUPPLY_MODULARITIES = "POWER_SUPPLY_MODULARITIES",
    POWER_SUPPLY_UNITS = "POWER_SUPPLY_UNITS",

    STORAGE_NAND_TYPES = "STORAGE_NAND_TYPES",
    STORAGE_CONNECTION_INTERFACES = "STORAGE_CONNECTION_INTERFACES",
    STORAGE_FORM_FACTORS = "STORAGE_FORM_FACTORS",
    STORAGE_UNITS = "STORAGE_UNITS",
}